name: 24/7 Forza Horizon 5 Live Stream

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Start Live Stream
      run: |
        ffmpeg -re -stream_loop -1 -i "video.mp4" \
        -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
        -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 \
        -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.YOUTUBE_STREAM_KEY }}"
