name: 24/7 Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Start Live Stream
      run: |
        gdown --id "1CeugCz7G5EJWGcoN5GW--HZ45TNzWiIF" -O video.mp4
        ffmpeg -re -stream_loop -1 -i video.mp4 -vcodec libx264 -pix_fmt yuv420p -maxrate 2048k -bufsize 2048k -framerate 30 -g 60 -acodec aac -ar 44100 -b:a 128k -f flv "${{ secrets.YOUTUBE_URL }}/${{ secrets.YOUTUBE_KEY }}"
